#!/bin/bash

dotfiles_dir="$HOME/dotfiles"
file_count="$(find "$dotfiles_dir" -maxdepth 1 -type f | wc -l)"

echo "Dotfiles information"
echo "User: $USER"
echo "Home directory: $HOME"
echo "Dotfiles path: $dotfiles_dir"
echo "Number of files in dotfiles: $file_count"
